extern void menu_do();
extern void menu_up();
extern void menu_down();
extern void menu_ptu(int);
extern void menu_ptd(int);
extern int menu_ptget();
extern char* menu_lineget(int);
extern const int menusize;
extern void menu_set(int,int);
extern int gridw;
